blank_issues_enabled: false
contact_links:
  - name: 💬 Ask Questions & Share Setups
    url: https://github.com/sanjay-np/nvim-yt-player/discussions
    about: Please ask questions and discuss configuration ideas in GitHub Discussions.
